project:
  name: "AcidenteInSight"
  version: "1.0"
  description: "Análise e predição de acidentes de trânsito com dados do Infosiga"
  author: "Diego Artero"

# Parser settings
parsing:
  base_url: "meruvulikith/90000-cars-data-from-1970-to-2024"
  output_format: "csv"
  save_path: "data\\raw\\"
  save_path_processed: "data\\processed\\"
  save_path_processed_formatted: "data\\processed\\formatted"
  save_path_processed_cleaned: "data\\processed\\cleaned"

# DataBases

postgres:
  host: "localhost"
  port: 5432
  database: "carsdb"
  user: "diego"
  password: "cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e"

mongodb:
  uri: "mongodb://localhost:27017/"
  database: "carsdb"
  collection: "cars"
# Machine learning configs
ml:
  model_type: "RandomForestClassifier"  # Opções: LogisticRegression, RandomForestClassifier, XGBoost, etc.
  test_size: 0.2
  random_state: 42
  features:
    - "horario"
    - "dia_semana"
    - "clima"
    - "tipo_acidente"
    - "idade_condutor"
    - "veiculo"

# Logging config
logging:
  level: "INFO"  
  log_file: "logs/Inteviewexercises.log"

# Data vis config
visualization:
  tool: "matplotlib"  
  theme: "darkgrid"
